services:
  postgres:
    container_name: em-postgres
    image: duvel/postgis:15-3.3 # postgres:15-alpine
    environment:
      - POSTGRES_HOST=${PRIMARY_POSTGRES_SERVER_URL}
      - POSTGRES_DB=${PRIMARY_POSTGRES_DB_NAME}
      - POSTGRES_USER=${PRIMARY_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${PRIMARY_POSTGRES_PASSWORD}
    ports:
      - ${PRIMARY_POSTGRES_SERVER_PORT}:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PRIMARY_POSTGRES_USERNAME} -d ${PRIMARY_POSTGRES_DB_NAME}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
